'use client';

import { use, useState, useEffect } from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { LiveViewContentBlock } from '@/wtf/Content/types';

// Dynamically import WTF to avoid SSR issues with Three.js
const WTF = dynamic(() => import('@/wtf/WTF'), {
  ssr: false,
  loading: () => (
    <div className="flex items-center justify-center min-h-screen bg-black text-white">
      <div className="text-center">
        <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-purple-500 mx-auto mb-4"></div>
        <p className="text-lg">Loading 3D Experience...</p>
      </div>
    </div>
  ),
});

interface PageProps {
  params: Promise<{
    date: string;
  }>;
}

interface EpisodeData {
  episodeId: string;
  title: string;
  date: string;
  description: string;
  isAutoGenerated: boolean;
  contentBlocks: LiveViewContentBlock[];
}

export default function EpisodePage({ params }: PageProps) {
  // Unwrap params using React.use()
  const { date } = use(params);

  const [content, setContent] = useState<LiveViewContentBlock[]>([]);
  const [episodeData, setEpisodeData] = useState<EpisodeData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchEpisode() {
      try {
        setLoading(true);
        setError(null);

        const response = await fetch(`/api/episodes/${date}`);

        if (!response.ok) {
          const errorData = await response.json();
          throw new Error(errorData.message || errorData.error || 'Failed to fetch episode');
        }

        const data: EpisodeData = await response.json();
        setEpisodeData(data);
        setContent(data.contentBlocks);
      } catch (err) {
        console.error('Failed to fetch episode:', err);
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    }

    fetchEpisode();
  }, [date]);

  // Loading state
  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-black text-white">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-t-2 border-b-2 border-purple-500 mx-auto mb-4"></div>
          <p className="text-lg">Loading episode for {date}...</p>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-black text-white">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-4">⚠️</div>
          <h1 className="text-2xl font-bold mb-4">Episode Not Found</h1>
          <p className="text-gray-400 mb-6">{error}</p>
          <Link
            href="/"
            className="inline-block px-6 py-3 bg-purple-600 hover:bg-purple-700 rounded-lg transition-colors"
          >
            Go Home
          </Link>
        </div>
      </div>
    );
  }

  // No content state
  if (!episodeData || content.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-black text-white">
        <div className="text-center max-w-md">
          <div className="text-6xl mb-4">📭</div>
          <h1 className="text-2xl font-bold mb-4">No Content Yet</h1>
          <p className="text-gray-400 mb-6">
            No posts have been tagged for {date}.
            <br />
            Start tagging posts on X.com with the 530 extension!
          </p>
          <Link
            href="/"
            className="inline-block px-6 py-3 bg-purple-600 hover:bg-purple-700 rounded-lg transition-colors"
          >
            Go Home
          </Link>
        </div>
      </div>
    );
  }

  // Success - render WTF
  return (
    <div className="w-full h-screen">
      {/* Episode Info Overlay (top-left) */}
      <div className="absolute top-4 left-4 z-50 bg-black/80 backdrop-blur-sm text-white px-4 py-2 rounded-lg">
        <h1 className="text-sm font-semibold">{episodeData.title}</h1>
        <p className="text-xs text-gray-400">
          {new Date(episodeData.date).toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
          })}
        </p>
      </div>

      {/* WTF 3D Viewer */}
      <WTF
        content={content}
        enableDevControls={process.env.NODE_ENV === 'development'}
        enableAudio={false}
        showLegend={true}
        showDetails={true}
        enableKeyboard={true}
        enableSwipe={true}
        onCategoryChange={(categoryId, categoryIndex) => {
          console.log('Category changed:', categoryId, categoryIndex);
          // Could add analytics here
        }}
        onItemChange={(itemId, itemIndex, itemData) => {
          console.log('Item changed:', itemId, itemIndex, itemData);
          // Could update URL or track analytics
        }}
        onItemClick={(itemData) => {
          console.log('Item clicked:', itemData);
          // Could open post in new tab
          if (itemData.content?.content_url) {
            window.open(itemData.content.content_url, '_blank');
          }
        }}
      />
    </div>
  );
}
